server:
  port: 8080
  
spring:
 datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3317/wumis?serverTimezone=GMT%2B8
    username: root
    password: root

 jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
      
mybatis:
  mapper-locations:
  - classpath*:/mappers/**/*.xml
  type-aliases-package: com.neusoft.wuyemis.baseinfo.model,com.neusoft.wuyemis.admin.model,com.neusoft.wuyemis.feeinfo.model
 
logging:
  level:
    com.neusoft.wuyemis.mapper: debug
    


